// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://beikfxipvaonauesxbuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlaWtmeGlwdmFvbmF1ZXN4YnVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzQ4MjksImV4cCI6MjA2NjI1MDgyOX0.t9ajv-hm2xFvgrkdO1nIClUbPmdxvA8fWF8WojH1-aY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);